config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  scope :manage do
    resources :manage_businesses, path: 'businesses'

    resources :system_logs, only: [:index, :show] do
      collection do
        get '/clear/logs', to: :clear_logs, as: :clear
        get '/clear/customers', to: :clear_customers, as: :clear_customers
        get '/clear/sessions', to: :clear_sessions, as: :clear_sessions
        get '/clear/everything', to: :clear_everything, as: :clear_everything
      end
    end

    get '/twilio/sub_account/:sid', to: 'manage#show_twilio_account', as: :show_twilio_account
    get '/twilio/stats', to: 'manage#show_twilio_stats', as: :manage_twilio_stats
    get '/twilio/test_client', to: 'manage#show_test_client', as: :manage_test_client

    get '/businesses', to: 'manage_businesses#index', as: :businesses
    get '/', to: 'manage#dashboard', as: :manage_dashboard
  end

  # Live handling of Customer Scheduler Sessions
  controller :live_scheduler do
    match '/twilio/voice', to: :voice, as: :twilio_voice, via: [:get, :post]
    match '/twilio/sms',   to: :sms, as: :twilio_sms, via: [:get, :post]
    match '/twilio/invalid/:device', to: :invalid_number, via: [:get, :post], as: :invalid_number
  end

  # Live handling of Customer Dynamic Tree Sessions
  controller :live_dynamo do
  end

  get '/businesses/:id/pending', to: 'businesses#pending', as: :business_pending
  get '/businesses/:id/dashboard', to: 'businesses#dashboard', as: :business_dashboard

  resources :businesses do
    get  '/buy/:number', to: 'numbers#buy_number', as: :buy_number
    post '/search', to: 'numbers#search', as: :search
    post '/send_sms', to: 'businesses#send_sms', as: :send_sms
    post '/make_a_call', to: 'businesses#make_a_call', as: :make_a_call

    resources :settings
    resources :time_sheets
    resources :time_entries
    resources :schedule_rules do
      collection do
        post '/', as: :create, to: :create
      end
    end
    resources :break_shifts
    resources :services
    resources :offices
    resources :numbers
    resources :users
  end

  scope :api do
    resources :break_shifts
    resources :businesses do
      resources :services
      resources :offices
    end
  end

  devise_scope :user do
    # tmp devise fix until we hook our links with javascript for :delete requests
    match 'users/sign_out' => "devise/sessions#destroy", via: [:get]
  end

  if Rails.env.development?
    get '/dev/clear', to: 'dev#clear'
  end

  root 'welcome#index'


end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  business_id :integer          not null
#  name        :string(255)      not null
#  description :text
#  duration    :integer          default(60)
#  created_at  :datetime
#  updated_at  :datetime
#  is_public   :boolean          default(TRUE)
#  sort_order  :integer
#

class Service < ActiveRecord::Base
  include Sortable

  belongs_to :business

  # Allow a Setting(s) to reference a service (polymorphically)
  has_many :settings, as: :supportable

  scope :business, ->(business) { where business_id: business.id  }
  after_create :update_ordering

  def disabled?
    true
  end

  alias_method :disabled, :disabled?

  def display_name
    name.titleize
  end

  def update_ordering
    if business
      PrioritySorter.sort! Service.business(business)
    end
  end

end

app/controllers/services_controller.rb
class ServicesController < BusinessesController

  load_and_authorize_resource :service, parent: false, except: [:create]
  skip_load_resource only: [:create]

  before_filter :set_current_sidebar
  sidebar  :services

  def index
    respond_with(@services)
  end

  def show
    respond_with(@service)
  end

  def new
    respond_with(@service)
  end

  def edit
  end

  def create
    authorize! :create, Service

    @service = Service.new(service_params)
    @service.save
    respond_with(@business, @service)
  end

  def update
    @service.update(service_params)
    respond_with(@business, @service)
  end

  def destroy
    @service.destroy
    respond_with(@business, @service)
  end

  private

  def set_current_sidebar
    @current_sidebar = :services
  end

  def service_params
    params.require(:service).permit(:business_id, :name, :description, :priority, :duration, :sort_order)
  end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= simple_form_for([@business, @service], class: 'form form-horizontal') do |f|

  - if @service.errors.any?
    #error_explanation
      %h2= "#{pluralize(@service.errors.count, "error")} prohibited this service from being saved:"
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  .form-inputs
    = f.hidden_field :business_id
    / Text input
    .form-group
      = f.label :name
      .controls
        = f.text_field :name, class: 'form-control'

    .form-group
      = f.label :description
      .controls
        = f.text_area :description, class: 'form-control'

    .form-group
      = f.label :duration
      .controls
        = f.number_field :duration, class: 'form-control'
    %hr/
    .form-group
      = f.input :is_public, class: 'form-control'

    %hr/
    .actions
      = f.submit 'Save Service', class: 'btn btn-success'

app/views/services/edit.html.haml
%p#notice= notice
%ol.breadcrumb
  %li
    = link_to 'Services', business_services_path
  %li.active
    = @service.name

%h2 Editing Service
%hr/
= render 'form'

%hr/
= link_to 'Show', [@business, @service]
\|
= link_to 'Back', business_services_path

app/views/services/index.html.haml
%p#notice= notice
%ol.breadcrumb
  %li
    = link_to 'Services', business_services_path
  %li.active Directory
%br/

%table.table.table-striped
  %tr
    %th Name
    %th Description
    %th Duration
    %th
    %th
    %th

  - if @services.empty?
    %tr
      %td{:colspan => "100"}
        %br/
        %strong No Services found for this Business.
        %p Please click the button below to add a Service for your Business.
  - @services.each do |service|
    %tr
      %td= service.name
      %td= service.description
      %td= service.duration
      %td= link_to 'Show', [@business, service]
      %td= link_to 'Edit', edit_business_service_path(@business, service)
      %td= link_to 'Destroy', [@business, service], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br/
%hr/

= link_to 'New Service', new_business_service_path(@business), class: 'btn btn-success'

app/views/services/new.html.haml
%p#notice= notice
%ol.breadcrumb
  %li
    = link_to 'Services', business_services_path
  %li.active New Service

%h2
  New Service for
  = @business.name
%hr/

= render 'form'
%hr/
= link_to 'Back', business_services_path, class: 'btn btn-link'

app/views/services/show.html.haml
%p#notice= notice
%ol.breadcrumb
  %li
    = link_to 'Services', business_services_path
  %li.active
    = @service.name

%h2
  Service for
  = @business.name
%hr/
%p
  %b Service Name:
  = @service.name
%p
  %b Description:
  = @service.description
%p
  %b Duration:
  = @service.duration

= link_to 'Edit', edit_business_service_path(@business, @service)
\|
= link_to 'Back', business_services_path