config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  scope :manage do
    resources :manage_businesses, path: 'businesses'

    resources :system_logs, only: [:index, :show] do
      collection do
        get '/clear/logs', to: :clear_logs, as: :clear
        get '/clear/customers', to: :clear_customers, as: :clear_customers
        get '/clear/sessions', to: :clear_sessions, as: :clear_sessions
        get '/clear/everything', to: :clear_everything, as: :clear_everything
      end
    end

    get '/twilio/sub_account/:sid', to: 'manage#show_twilio_account', as: :show_twilio_account
    get '/twilio/stats', to: 'manage#show_twilio_stats', as: :manage_twilio_stats
    get '/twilio/test_client', to: 'manage#show_test_client', as: :manage_test_client

    get '/businesses', to: 'manage_businesses#index', as: :businesses
    get '/', to: 'manage#dashboard', as: :manage_dashboard
  end

  # Live handling of Customer Scheduler Sessions
  controller :live_scheduler do
    match '/twilio/voice', to: :voice, as: :twilio_voice, via: [:get, :post]
    match '/twilio/sms',   to: :sms, as: :twilio_sms, via: [:get, :post]
    match '/twilio/invalid/:device', to: :invalid_number, via: [:get, :post], as: :invalid_number
  end

  # Live handling of Customer Dynamic Tree Sessions
  controller :live_dynamo do
  end

  get '/businesses/:id/pending', to: 'businesses#pending', as: :business_pending
  get '/businesses/:id/dashboard', to: 'businesses#dashboard', as: :business_dashboard

  resources :businesses do
    get  '/buy/:number', to: 'numbers#buy_number', as: :buy_number
    post '/search', to: 'numbers#search', as: :search
    post '/send_sms', to: 'businesses#send_sms', as: :send_sms
    post '/make_a_call', to: 'businesses#make_a_call', as: :make_a_call

    resources :settings
    resources :time_sheets
    resources :time_entries
    resources :schedule_rules do
      collection do
        post '/', as: :create, to: :create
      end
    end
    resources :break_shifts
    resources :services
    resources :offices
    resources :numbers
    resources :users
  end

  scope :api do
    resources :break_shifts
    resources :businesses do
      resources :services
      resources :offices
    end
  end

  devise_scope :user do
    # tmp devise fix until we hook our links with javascript for :delete requests
    match 'users/sign_out' => "devise/sessions#destroy", via: [:get]
  end

  if Rails.env.development?
    get '/dev/clear', to: 'dev#clear'
  end

  root 'welcome#index'


end

app/models/schedule_rule.rb
# == Schema Information
#
# Table name: schedule_rules
#
#  id                  :integer          not null, primary key
#  service_provider_id :integer          not null
#  business_id         :integer          not null
#  is_active           :boolean          default(TRUE)
#  created_at          :datetime
#  updated_at          :datetime
#

class ScheduleRule < ActiveRecord::Base

  belongs_to :business
  belongs_to :service_provider,
    class_name: 'User',
    foreign_key: 'service_provider_id'

  has_many :break_shifts
  has_many :break_services,
    :through => :break_shifts

  has_many :time_sheets,
    :dependent => :destroy

  has_many :time_entries,
    :through => :time_sheets

  attr_accessor :services

  validates_presence_of :service_provider
  validates_presence_of :business

  validates_uniqueness_of :service_provider_id

  def work_hours
    @work_hours_cache ||= time_sheets.map(&:entry_hours).sum
  end

  def break_hours
    @break_hours_cache ||= break_shifts.map(&:hours).sum
  end

end

app/controllers/schedule_rules_controller.rb
class ScheduleRulesController < BusinessesController

  before_filter :set_sidebar
  before_filter :load_business, only: [:create]

  load_and_authorize_resource :schedule_rule

  before_filter :provide_create_with_schedule_rule, only: [:create]
  before_filter :provide_business_basics, only: [:new, :edit, :show]
  before_filter :validate_requirements, only: [:new, :edit, :show]

  include EntryHelper
  helper :entry
  sidebar :schedule_rules


  def index
    @schedule_rules = ScheduleRule.where(business_id: @business.id)
    respond_with(@schedule_rules)
  end

  def show
    respond_with(@schedule_rule)
  end

  def new
    respond_with(@business, @schedule_rule)
  end

  def edit
  end

  def create
    @schedule_rule.service_provider_id = params[:schedule_rule][:service_provider_id]
    @schedule_rule.business_id = @business.id

    if @schedule_rule.save
      @s = @schedule_rule # shortcut it
      @bid = @business.id

      sheets = params[:schedule_rule][:sheets] and params[:schedule_rule][:sheets].dup

      # Create TimeSheet(s) on the ScheduleRule
      sheets.each do |sheet|
        time_sheet = @s.time_sheets.create!(business_id: @bid)

        # Create TimeSheetServices if any services were specified
        sheet[:services].each do |service|
            TimeSheetService.create!(
              service_id: service,
              business_id: @bid,
              time_sheet_id: time_sheet.id)
        end if sheet[:services].present?

        # Create Time Sheet Entries
        sheet[:entries].each do |entry|
          entry[:business_id]   = @bid
          entry[:time_sheet_id] = time_sheet.id

          entry = convert_meridians(entry)

          te = TimeEntry.create! entry.permit!
          raise te.errors.to_json if not te.persisted?

        end if sheet[:entries]

      end if sheets

      # Create BreakShift(s) on the ScheduleRule
      params[:schedule_rule][:breaks].each do |brk|
        brk[:business_id] = @bid
        brk[:schedule_rule_id] = @s.id

        brk = convert_meridians(brk)
        brk = convert_date_ranges(brk)
        bs = @s.break_shifts.create! brk.except(:services, :offices).permit!

        raise bs.errors.to_json if not bs.persisted?

        brk[:services].each do |service_id|
          bs.break_services.create!(break_shift_id: bs.id, service_id: service_id, business_id: @bid)
        end if brk[:services].present?

        brk[:offices].each do |office_id|
          bs.break_offices.create!(break_shift_id: bs.id, office_id: office_id, business_id: @bid)
        end if brk[:offices].present?


      end if params[:schedule_rule][:breaks].present?

    end

    flash[:success] = "Schedule Rule saved"
    respond_with(@business, @schedule_rule) do |format|
      format.js { render json: @schedule_rule }
    end
  end

  def update
    @schedule_rule.update(schedule_rule_params)
    respond_with(@business, @schedule_rule)
  end

  def destroy
    @schedule_rule.destroy
    respond_with(@business, @schedule_rule)
  end

  private

  def provide_business_basics
    @service_providers = User.business(@business).service_providers
    @services = Service.business(@business)
    @offices = Office.business(@business)
  end

  def validate_requirements
    if @service_providers.empty? and params[:action] != "show"
      return redirect_to business_users_path,
        alert: "You must have at least one AVAILABLE Service Provider before creating a Schedule Rule"
    end

    if @services.empty?
      return redirect_to business_services_path,
        alert: "You must have at least one Service before creating a Schedule Rule"
    end

    if @offices.empty?
      return redirect_to business_offices_path,
        alert: "You must have at least one Office before creating a Schedule Rule"
    end
  end

  def provide_create_with_schedule_rule
    if authorize! :create, ScheduleRule
      @schedule_rule = ScheduleRule.new
      @schedule_rule.attributes = schedule_rule_params.dup
    end
  end

  def set_sidebar
    set_current_sidebar :schedule_rules
    @current_sidebar = :schedule_rules
  end

  def schedule_rule_params
    params.require(:schedule_rule).except(:sheets, :offices)
    .permit(:service_provider_id, :business_id)
  end
end

app/helpers/schedule_rules_helper.rb
module ScheduleRulesHelper
end

app/views/schedule_rules/_form.html.haml
#schedule-container
  = simple_form_for([@business, @schedule_rule], class: 'form') do |f|
    = f.hidden_field :business_id
    = f.hidden_field :service_provider_id

    - if @schedule_rule.errors.any?
      #error_explanation
        %h2= "#{pluralize(@schedule_rule.errors.count, "error")} prohibited this schedule_rule from being saved:"
        %ul
          - @schedule_rule.errors.full_messages.each do |msg|
            %li= msg

    = form_error_messages(@schedule_rule)

    .form-inputs
      / Text input
      .form-group.row.service-providers
        .col-lg-3.left
          = f.label :is_schedule_public, 'Service Provider'
        .col-lg-9.right
          - unavailable_providers = @service_providers.select(&:not_available_for_scheduling).map(&:id)
          = f.collection_select :service_provider_id, @service_providers, :id, :display_name, { prompt: "Select a Service Provider (User Staff)", selected: @schedule_rule.service_provider_id, disabled: unavailable_providers }, class: 'bootstrap-select', data: { style: 'btn-info', width: '300px', unavailable: unavailable_providers, placeholder: "Select a Provider" }
        .col-lg-12.right
          %br/
          .help
            A Service Provider may only be used once, but may have multiple Time Sheets in a single Schedule Rule.
            %br
      %br
      %br
      -# Nav tabs
      %ul.nav.nav-tabs{:role => "tablist"}
        %li.active{:role => "presentation"}
          %a{id: "availability-tab", "aria-controls" => "availability", "data-toggle" => "tab", :href => "#availability", :role => "tab"}
            Availability
            %span.count.muted (0)
        %li{:role => "presentation"}
          %a{id: "breaks-tab", "aria-controls" => "breaks", "data-toggle" => "tab", :href => "#breaks", :role => "tab"}
            Breaks
            %span.count.muted (0)

      .tab-content
        #availability.top-time-sheet-entries.row.active.tab-pane{role: "tabpanel"}
          .btn.btn-add-time-sheet.btn-link.hidden.pull-right
            %i.fa.fa-plus
            Add another Time Sheet
          .clear
        #breaks.break-entries.row.tab-pane{role: "tabpanel"}
          %br/
          %br/

      .time-sheet-spinner
        %i.fa.fa-spinner.fa-spin
        Loading...

      .alert.alert-info.hidden
        Would you like to add some breaks?

    %br/
    .actions

      .btn.btn-save-everything.btn-default.pull-right.btn-lg.hidden
        %i.fa.fa-check
        Save Schedule

app/views/schedule_rules/create.html.haml
creating schedule rule...

app/views/schedule_rules/edit.html.haml
%p#notice= notice

%p
  %b Service provider:
  = @schedule_rule.service_provider.display_name
%hr/
%h4
  Time entries

%table.table.table-horizontal.table-striped
  %thead
    %tr
      %th DAY
      %th START HOUR
      %th START MINUTE
      %th END HOUR
      %th END MINUTE
      %th OFFICE
  %tbody
    - @schedule_rule.time_sheets.each do |time_sheet|
      - time_sheet.time_entries.each do |entry|
        %tr
          %td= entry.day_title
          %td= entry.start_hour
          %td= entry.start_minute
          %td= entry.end_hour
          %td= entry.end_minute
          - if entry.office
            %td= entry.office.name
          - else
            %td All Offices

%hr/
%h4
  Break entries

%table.table.table-horizontal.table-striped
  %thead
    %tr
      %th DAY
      %th START HOUR
      %th START MINUTE
      %th END HOUR
      %th END MINUTE
      %th FLOAT
      %th OFFICE
      %th SERVICES
  %tbody
    - @schedule_rule.break_shifts.each do |entry|
      %tr
        %td= entry.day_title
        %td= entry.start_hour
        %td= entry.start_minute
        %td= entry.end_hour
        %td= entry.end_minute
        %td= entry.floating_break
        - if entry.office
          %td= entry.office.name
        - else
          %td All Offices

        - if entry.break_services.empty?
          %td All Services
        - else
          %td
            - entry.break_services.each do |service|
              .label.label-success
                =service.service.name
%br/
%br/
%pre
  Full details and Live Editor (based on the create form) coming soon
  %br/

%hr/
= link_to 'Back', business_schedule_rules_path(@business)

app/views/schedule_rules/index.html.haml
%ol.breadcrumb
  %li
    %a{:href => business_schedule_rules_path(@business)} Schedule Rules
  %li.active Directory

.pull-left
  = link_to new_business_schedule_rule_path, class: 'btn btn-default' do
    %i.fa.fa-plus-circle
    New Schedule Rule

.view-archived.pull-right
  .btn.btn-link.muted
    %i.fa.fa-sort
    Sort Order
  %span.muted
    \|
  .btn.btn-link.muted
    %i.fa.fa-archive
    View Archived Rules
.clear
%br/

%table.table.table-striped
  %tr
    %th{style: 'width:16%'} Service Provider
    %th{style: 'width:16%'} Offices
    %th{style: 'width:16%'} Work Hours
    %th{style: 'width:16%'} Break Hours
    / %th{style: 'width:20%'} Last Updated
    %th.actions{style: 'width:32%'} &nbsp; Actions
    %th
  - if @schedule_rules.empty?
    %tr
      %td{colspan: 100}
        %p
          %h3 No Schedule Rules were found for your Business.
          %p Click the button above to easily add a new Schedule Rule.
  - @schedule_rules.each do |schedule_rule|
    %tr
      %td{ colspan: 100 }
        .schedule-rule-entry
          .row
            .col-lg-2.col-md-2.col-sm-2.col-xs-2
              - if schedule_rule.service_provider
                = schedule_rule.service_provider.display_name
              - else
                %span.red Unavailable
            .col-lg-2.col-md-2.col-sm-2.col-xs-2
              All
            .col-lg-2.col-md-2.col-sm-2.col-xs-2
              = schedule_rule.work_hours
              hr
              %span.muted /week

            .col-lg-2.col-md-2.col-sm-2.col-xs-2{class: (schedule_rule.break_hours == 0) ? 'red' : '' }
              = schedule_rule.break_hours
              hr
              - if schedule_rule.break_hours > 0
                %span.muted /week

            .actions.col-lg-4.col-md-4.col-sm-4.col-xs-4.pull-right
              / .last-updated
              /   = time_ago_in_words schedule_rule.updated_at
              /   ago

              = link_to business_schedule_rule_path(@business, schedule_rule), :method => :delete, :data => { :confirm => 'Are you sure you want to DELETE this Rule?' }, class: 'pull-right delete btn btn-xs btn-link' do
                %i.fa.fa-trash-o.red
              = link_to 'View Timesheets', business_schedule_rule_path(@business, schedule_rule), class: 'btn btn-xs btn-default pull-right open'

app/views/schedule_rules/new.html.haml
%ol.breadcrumb
  %li
    %a{:href => business_schedule_rules_path(@business)} Schedule Rules
  %li.active New Schedule Rule

%hr/


= render 'form'

%br/
%br/
%hr/

= link_to 'Back', business_schedule_rules_path, class: 'btn btn-link'

- content_for :javascript do
  :coffeescript
    Scp.Data ||=
      services: #{@services.to_json}
      offices: #{@offices.to_json}
      providers: #{@service_providers.to_json}

    # Start the ScheduleForm UI
    $ -> window['view'] = new Scplanner.Views.Schedules.NewView()

app/views/schedule_rules/show.html.haml
%ol.breadcrumb
  %li
    %a{:href => business_schedule_rules_path(@business)} Schedule Rules
  %li.active Editing Schedule Rule

%hr/
= render 'form'

%br/
%br/
%hr/

= link_to 'Back', business_schedule_rules_path, class: 'btn btn-link'

- content_for :javascript do
  :coffeescript
    window.Scp ||= {}

    Scp.Data =
      services: #{@services.to_json}
      offices: #{@offices.to_json}
      providers: #{@service_providers.to_json}

    Scp.Preload = new Scp.Services.PreloadService
      schedule_rule: #{@schedule_rule.to_json}
      time_sheets: #{@schedule_rule.time_sheets.to_json}
      time_sheet_services: #{@schedule_rule.time_sheets.map(&:time_sheet_services).map { |tss| tss.map(&:id) }.to_json }
      time_entries:   #{@schedule_rule.time_sheets.map(&:time_entries).map{ |te| te.all }.flatten.to_json }
      break_shifts:   #{@schedule_rule.break_shifts.to_json}
      break_services: #{@schedule_rule.break_services.to_json}
      break_offices:  #{@schedule_rule.break_shifts.map(&:break_offices).map { |bo| bo }.to_json }

    Scp.Preload.go()

    # Start the ScheduleForm UI
    $ -> window['view'] = new Scplanner.Views.Schedules.NewView()