config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  scope :manage do
    resources :manage_businesses, path: 'businesses'

    resources :system_logs, only: [:index, :show] do
      collection do
        get '/clear/logs', to: :clear_logs, as: :clear
        get '/clear/customers', to: :clear_customers, as: :clear_customers
        get '/clear/sessions', to: :clear_sessions, as: :clear_sessions
        get '/clear/everything', to: :clear_everything, as: :clear_everything
      end
    end

    get '/twilio/sub_account/:sid', to: 'manage#show_twilio_account', as: :show_twilio_account
    get '/twilio/stats', to: 'manage#show_twilio_stats', as: :manage_twilio_stats
    get '/twilio/test_client', to: 'manage#show_test_client', as: :manage_test_client

    get '/businesses', to: 'manage_businesses#index', as: :businesses
    get '/', to: 'manage#dashboard', as: :manage_dashboard
  end

  # Live handling of Customer Scheduler Sessions
  controller :live_scheduler do
    match '/twilio/voice', to: :voice, as: :twilio_voice, via: [:get, :post]
    match '/twilio/sms',   to: :sms, as: :twilio_sms, via: [:get, :post]
    match '/twilio/invalid/:device', to: :invalid_number, via: [:get, :post], as: :invalid_number
  end

  # Live handling of Customer Dynamic Tree Sessions
  controller :live_dynamo do
  end

  get '/businesses/:id/pending', to: 'businesses#pending', as: :business_pending
  get '/businesses/:id/dashboard', to: 'businesses#dashboard', as: :business_dashboard

  resources :businesses do
    get  '/buy/:number', to: 'numbers#buy_number', as: :buy_number
    post '/search', to: 'numbers#search', as: :search
    post '/send_sms', to: 'businesses#send_sms', as: :send_sms
    post '/make_a_call', to: 'businesses#make_a_call', as: :make_a_call

    resources :settings
    resources :time_sheets
    resources :time_entries
    resources :schedule_rules do
      collection do
        post '/', as: :create, to: :create
      end
    end
    resources :break_shifts
    resources :services
    resources :offices
    resources :numbers
    resources :users
  end

  scope :api do
    resources :break_shifts
    resources :businesses do
      resources :services
      resources :offices
    end
  end

  devise_scope :user do
    # tmp devise fix until we hook our links with javascript for :delete requests
    match 'users/sign_out' => "devise/sessions#destroy", via: [:get]
  end

  if Rails.env.development?
    get '/dev/clear', to: 'dev#clear'
  end

  root 'welcome#index'


end

app/models/number.rb
# == Schema Information
#
# Table name: numbers
#
#  id                 :integer          not null, primary key
#  sub_account_id     :integer
#  office_id          :integer
#  phone_number       :string(255)      not null
#  sid                :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  sms_url            :string(255)
#  voice_url          :string(255)
#  status_url         :string(255)
#  voice_fallback_url :string(255)
#  sms_fallback_url   :string(255)
#  friendly_name      :string(255)
#  capabilities       :integer
#  account_sid        :string(255)
#  voice_method       :string(255)
#  sms_method         :string(255)
#

class Number < ActiveRecord::Base
  belongs_to :sub_account
  belongs_to :office

  validates_presence_of :sub_account
  validates_presence_of :sid

  after_save :update_remote_source

  def display_name
    org = (office and office.display_name) || sub_account.business.display_name
    "#{org} / #{phone_number}"
  end

  def update_remote_source
    unless Rails.env.test?
      number_params = {
        sid: sid,
        sub_account_sid: sub_account.sid,
        sms_url: sms_url,
        voice_url: voice_url,
        status_url: status_url,
        friendly_name: friendly_name,
        sms_method: sms_method,
        voice_method: voice_method
      }
      Skej::Twilio.update_number(number_params)
    end
  end
end

app/controllers/numbers_controller.rb
class NumbersController < BusinessesController

  # Load Numbers via CanCan factory
  load_and_authorize_resource

  layout 'business_console'

  sidebar  :numbers

  def index
    authorize! :read, Number
    @numbers = @business.numbers
    respond_with(@business, @numbers)
  end

  def show
    respond_with(@business, @number)
  end

  def new
    @sub_account = @business.sub_account
    respond_to do |format|
      format.html {}
    end
  end

  def edit
  end

  def create
    @number = Number.new(number_params)
    @number.save
    respond_with(@business, @number)
  end

  def update
    @number.update(number_params)
    respond_with(@business, @number)
  end

  def destroy
    @number.destroy
    respond_with(@business, @number)
  end

  def search
    @sub_account = @business.sub_account

    search_params = {}

    %w[in_postal_code near_number contains].each do |p|
      search_params[p] = params[:search][p] unless params[:search][p].nil? || params[:search][p].empty?
    end

    @numbers = @sub_account.search_numbers(search_params)

    respond_to do |format|
      format.js {}
    end
  end

  def buy_number

    begin
      @number = @business.sub_account.buy_number(params[:number])
      @success = true

    rescue Twilio::REST::RequestError => e
      @success = false
      logger.error(e.message)
      return redirect_to new_business_number_path(@business),
        :alert => "Sorry, the Number #{params[:number]} is no longer available."
    end
    
    path = business_numbers_path(@business)

    respond_to do |format|
      format.html { 
        if @success
          redirect_to path , :success => "You successfully puchased #{params[:number]}"
        else
          redirect_to path , :alert => "Oops, something happened. Please try again or Contact Support, Thanks!"
        end
      }

      format.json {
        render json: { success: @success, number: @number }
      }
    end
  end


  private

  def number_params
    params.require(:number).permit(:sub_account_id, :sid, :auth_token, :office_id)
  end
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/numbers/_callModal.html.haml
#callModal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Make a Call
      = simple_form_for :info , :url => make_a_call_path(business.slug)  do |f|
        .modal-body
          = f.input :to
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          = f.submit "Call" , class: "btn btn-primary"

app/views/numbers/_form.html.haml
= simple_form_for([@business,@number]) do |f|
  = f.error_notification
  .form-inputs
    = f.input :phone_number, input_html: { disabled: true }
    %br/
    %span.small.muted
      Editing of Inbound Numbers is currently not supported.
      %br/
      However you are free to create a new Number.
    %hr
  .form-inputs
    = f.association :office, collection: Office.business(@business), prompt: 'All Offices', label: 'Specific Office Designation'
    %hr/
  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/numbers/_msgModal.html.haml
#msgModal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Send Message
      = simple_form_for :message , :url => send_sms_path(business.slug)  do |f|
        .modal-body
          = f.input :to
          = f.input :body , :as => :text
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
          = f.submit "Send SMS" , class: "btn btn-primary"

app/views/numbers/_numbers.html.haml
%table.table.table-stripped
  %thead
    %tr
      %th Phone Number
      %th.actions Actions
  %tbody
    - numbers.each do |num|
      %tr
        %td
          = num.phone_number
        %td
          = link_to 'Buy' , business_buy_number_path(business, :number => num.phone_number) , class: 'btn btn-success btn-xs'

app/views/numbers/edit.html.haml
%h1
  Editing number
  = @number.phone_number
%hr/

= render 'form'

%hr/
= link_to 'Back', business_numbers_path(@business), class: 'btn btn-default'

app/views/numbers/index.html.haml
%p#notice= notice
%ol.breadcrumb
  %li
    = link_to 'Numbers', business_numbers_path
  %li.active Directory

%br/


%table.table.table-striped
  %thead
    %tr
      %th Number
      %th Office
      %th.actions{:colspan => "3"}
  %tbody
    - if @numbers.empty?
      %tr
        %td.muted{:colspan => "100"}
          There are currently no Inbound Numbers associated with your Business.
    - @numbers.each do |number|
      %tr
        %td= number.phone_number
        %td
          - if number.office
            = number.office
          - else
            %span.muted
              All Offices
        %td.actions
          = link_to 'Show', business_number_path(@business, number), class: 'btn btn-default btn-xs'
          = link_to 'Edit', edit_business_number_path(@business, number), class: 'btn btn-warning btn-xs'
          = link_to 'Destroy', business_number_path(@business, number), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs'

%br/
%hr/
- if can? :create, Number
  = link_to 'Buy New Number', new_business_number_path(@business), class: 'btn btn-success'
  %br/
  %br/
  %span.muted.small Warning: Twilio will instantly charge your account $1 for each Number purchased.

- content_for :javascript do
  :coffeescript
    window.numbers = #{@numbers.to_json}

app/views/numbers/new.html.haml
.alert.alert-danger
  Warning: Twilio will 
  %strong Instantly 
  charge your account $1 for each Number purchased.
%hr/
.container
  .row
    #loading{:style => "display:none;text-align: center;"}
      = image_tag 'loading.gif'
  .row
    .col-md-3
      = simple_form_for :search , :url => business_search_path(@business),           |
        :html => { :role => 'form', class: 'number-search', :remote => true } do |f| |
        = f.input :in_postal_code, :label => 'Near US postal code', :hint => "e.g. 21201"
        = f.input :near_number, :label => 'Near this other number', :hint => "e.g. +14439555458"
        = f.input :contains, :label => 'Matching the pattern', :hint => "e.g. 415***EPIC"
        = f.submit 'Search', class: 'btn btn-success'
        = link_to 'Back', business_numbers_path(@business), class: 'btn btn-default'
    #number-search-results.col-md-8

app/views/numbers/search.js.haml
$("#loading").css("display","none")
$("#number-search-results").addClass("well")
$("#number-search-results").html("#{j(render( :partial => 'numbers', :locals => { :numbers => @numbers, :business => @business }))}")

app/views/numbers/show.html.haml
%p#notice= notice
%p
  %h1 Designated Office:
  %h3
    - if @number.office
      = @number.office.name
    - else
      All Offices

%hr/
%p
  %strong Number:
  = @number.phone_number
%p
  %strong SID:
  = @number.sid
%p
  %strong SMS Endpoint:
  = @number.sms_url
%p
  %strong Voice Endpoint:
  = @number.voice_url

%hr
= link_to 'Back', business_numbers_path(@business), class: 'btn btn-default'
&nbsp;
= link_to 'Edit', edit_business_number_path(@business, @number), class: 'btn btn-warning'