config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  scope :manage do
    resources :manage_businesses, path: 'businesses'

    resources :system_logs, only: [:index, :show] do
      collection do
        get '/clear/logs', to: :clear_logs, as: :clear
        get '/clear/customers', to: :clear_customers, as: :clear_customers
        get '/clear/sessions', to: :clear_sessions, as: :clear_sessions
        get '/clear/everything', to: :clear_everything, as: :clear_everything
      end
    end

    get '/twilio/sub_account/:sid', to: 'manage#show_twilio_account', as: :show_twilio_account
    get '/twilio/stats', to: 'manage#show_twilio_stats', as: :manage_twilio_stats
    get '/twilio/test_client', to: 'manage#show_test_client', as: :manage_test_client

    get '/businesses', to: 'manage_businesses#index', as: :businesses
    get '/', to: 'manage#dashboard', as: :manage_dashboard
  end

  # Live handling of Customer Scheduler Sessions
  controller :live_scheduler do
    match '/twilio/voice', to: :voice, as: :twilio_voice, via: [:get, :post]
    match '/twilio/sms',   to: :sms, as: :twilio_sms, via: [:get, :post]
    match '/twilio/invalid/:device', to: :invalid_number, via: [:get, :post], as: :invalid_number
  end

  # Live handling of Customer Dynamic Tree Sessions
  controller :live_dynamo do
  end

  get '/businesses/:id/pending', to: 'businesses#pending', as: :business_pending
  get '/businesses/:id/dashboard', to: 'businesses#dashboard', as: :business_dashboard

  resources :businesses do
    get  '/buy/:number', to: 'numbers#buy_number', as: :buy_number
    post '/search', to: 'numbers#search', as: :search
    post '/send_sms', to: 'businesses#send_sms', as: :send_sms
    post '/make_a_call', to: 'businesses#make_a_call', as: :make_a_call

    resources :settings
    resources :time_sheets
    resources :time_entries
    resources :schedule_rules do
      collection do
        post '/', as: :create, to: :create
      end
    end
    resources :break_shifts
    resources :services
    resources :offices
    resources :numbers
    resources :users
  end

  scope :api do
    resources :break_shifts
    resources :businesses do
      resources :services
      resources :offices
    end
  end

  devise_scope :user do
    # tmp devise fix until we hook our links with javascript for :delete requests
    match 'users/sign_out' => "devise/sessions#destroy", via: [:get]
  end

  if Rails.env.development?
    get '/dev/clear', to: 'dev#clear'
  end

  root 'welcome#index'


end

app/models/setting.rb
# == Schema Information
#
# Table name: settings
#
#  id               :integer          not null, primary key
#  business_id      :integer          not null
#  key              :string(255)      not null
#  value            :string(255)      not null
#  description      :text
#  is_active        :boolean          default(TRUE)
#  created_at       :datetime
#  updated_at       :datetime
#  supportable_id   :integer
#  supportable_type :string(255)
#

class Setting < ActiveRecord::Base
  belongs_to :business

  belongs_to :supportable, polymorphic: true

  validates_presence_of :key
  validates_presence_of :business
  validates_uniqueness_of :business_id, :scope => :key

  scope :business, ->(business) { where business_id: business.id }
  scope :key, ->(key) { where key: key }

  # Todo: refactor these constants into enums?
  # But.. we need direct access to these throughout the system,
  # so this appears to be the path to least friction.

  # Constant KEYS
  PRIORITY                = 'priority'
  USER_SELECTION          = 'user_selection'
  USER_SELECTION_PRIORITY = 'user_selection_priority'
  SERVICE_SELECTION       = 'service_selection'
  OFFICE_SELECTION        = 'office_selection'

  # Constant VALUES for OFFICE_SELECTION
  OFFICE_SELECTION_ASK             = 'office_ask'
  OFFICE_SELECTION_ASK_AND_ASSUME  = 'office_ask_and_assume'
  OFFICE_SELECTION_ASSUME          = 'office_assume'

  # Constant VALUES for SERVICE_SELECTION
  SERVICE_SELECTION_ASK            = 'service_ask'
  SERVICE_SELECTION_ASK_AND_ASSUME = 'service_ask_and_assume'
  SERVICE_SELECTION_ASSUME         = 'service_assume'

  # Constant VALUES for USER_SELECTION
  USER_SELECTION_FULL_CONTROL = 'user_selection_full_control'
  USER_SELECTION_EXPRESS_I    = 'user_selection_express_1'
  USER_SELECTION_EXPRESS_II   = 'user_selection_express_2'
  USER_SELECTION_EXPRESS_III  = 'user_selection_express_3'

  # Constant VALUES for USER_SELECTION_PRIORITY
  USER_SELECTION_PRIORITY_RANDOM    = 'user_selection_priority_random'
  USER_SELECTION_PRIORITY_AUTOMATIC = 'user_selection_priority_automatic'


  SELECTION_KEYS = [ PRIORITY,
                     USER_SELECTION,
                     USER_SELECTION_PRIORITY,
                     SERVICE_SELECTION,
                     OFFICE_SELECTION ]

  PRIORITY_VALUES = []

  USER_SELECTION_VALUES = [ USER_SELECTION_FULL_CONTROL,
                            USER_SELECTION_EXPRESS_I,
                            USER_SELECTION_EXPRESS_II,
                            USER_SELECTION_EXPRESS_III ]

  USER_SELECTION_PRIORITY_VALUES = [ USER_SELECTION_PRIORITY_RANDOM,
                                     USER_SELECTION_PRIORITY_AUTOMATIC ]

  SERVICE_SELECTION_VALUES = [ SERVICE_SELECTION_ASK,
                               SERVICE_SELECTION_ASK_AND_ASSUME,
                               SERVICE_SELECTION_ASSUME ]

  OFFICE_SELECTION_VALUES = [ OFFICE_SELECTION_ASK,
                              OFFICE_SELECTION_ASK_AND_ASSUME,
                              OFFICE_SELECTION_ASSUME ]

  class << self

    def create_default(opts = {})
      create({ key: opts[:key],
               value: default_value_for(opts[:key]),
               business_id: opts[:business].id })
    end

    def default_value_for(key)
      ("Setting::#{key.upcase}_VALUES".constantize).first
    end

    def valid_key? (key)
      SELECTION_KEYS.map{ |k| ("Setting::" + k.to_s.upcase).constantize }.include? key.to_s.downcase
    end

    def get_or_create(key, opts = {})
      existing = Setting.where(key: key, business_id: opts[:business_id]).first
      return existing if existing

      raise "business_id is required for first time generation" if opts[:business_id].nil?
      raise "value is required for first time generation" if opts[:value].nil? and opts[:default_value].nil?

      install_key! key, opts
    end

    def install_key!(key, opts)
      # Translate any instances into foreign keys
      if opts[:business].present? and opts[:business].kind_of? Business
        opts[:business_id] = opts[:business].id
      end

      raise 'A business must be specified via :business or :business_id' unless opts[:business_id].present?

      create(key: key,
             value: (opts[:value] || opts[:default_value]),
             business_id: opts[:business_id])
    end
  end

  def is(what)
    value == what
  end
  alias_attribute :is?, :is

  def to_b
    value.to_b
  end

  def office_selection_type=(type)
    self.key = OFFICE_SELECTION
    self.value = type
  end

  def service_selection_type=(type)
    self.key = SERVICE_SELECTION
    self.value = type
  end

  def user_selection_type=(type)
    self.key = USER_SELECTION
    self.value = type
  end

  def user_selection_priority_type=(type)
    self.key = PRIORITY
    self.value = type
  end

  def user_selection_full_control?
    value == USER_SELECTION_FULL_CONTROL
  end

end

app/controllers/settings_controller.rb
class SettingsController < BusinessesController

  #load_and_authorize_resource
  skip_load_resource :setting
  skip_load_resource :manage_business

  before_filter :set_current_sidebar
  before_filter :load_setting, only: [:update]
  before_filter :load_settings, only: [:index, :show]

  rescue_from CanCan::AccessDenied do |exception|

    path = root_path
    Rails.logger.error "User(#{current_user and current_user.display_name}) CanCan::AccessDenied: #{exception.message}"

    if current_user
      path = business_settings_path(current_user.business)
    end

    redirect_to path, :alert => "Sorry, your not authorized for that Setting"
  end

  def index
    @settings = Setting.business(@business)
    @services = Service.business(@business)
    @offices  = Office.business(@business)

    # Set the default visual radio input to ask,
    # when we will be skipping service selection (< 2)
    if @services.length < 2
      @service_selection.value = Setting::SERVICE_SELECTION_ASK
    end

    if @service_providers.length < 2
      @user_selection_priority.value = Setting::USER_SELECTION_PRIORITY_RANDOM
    end

  end

  def update

    if @setting.present? and can? :manage, @setting
      @setting.update! setting_params
    end

    if params[:setting_aux].present?
      aux = params.require(:setting_aux).permit!
      setting_auxilary = Setting.where(key: aux[:key]).first
      setting_auxilary.update! value: aux[aux[:value]]
    end

    hash = "##{params[:hash] || "service-selection"}"

    if @setting.errors.empty?
      flash[:success] = "#{hash.gsub('#','').titleize} Settings have been saved successfully"
    end

    respond_with @business, @setting, location: business_settings_path(@business) << hash
  end

  def show
    redirect_to business_settings_path(@business)
  end


  private

  def set_current_sidebar
    @current_sidebar = :settings
  end

  def load_setting
    @setting = Setting.find(params[:id])
    authorize! :read, @setting
  end

  def load_settings
    if can? :read, Setting
      @office_selection = Setting.get_or_create Setting::OFFICE_SELECTION,
        business_id: @business.id,
        default_value: Setting::OFFICE_SELECTION_ASK

      @service_selection = Setting.get_or_create Setting::SERVICE_SELECTION,
        business_id: @business.id,
        default_value: Setting::SERVICE_SELECTION_ASK

      @user_selection = Setting.get_or_create Setting::USER_SELECTION,
        business_id: @business.id,
        default_value: Setting::USER_SELECTION_FULL_CONTROL

      @user_selection_priority = Setting.get_or_create Setting::USER_SELECTION_PRIORITY,
        business_id: @business.id,
        default_value: Setting::USER_SELECTION_PRIORITY_RANDOM

      @service_providers = PrioritySorter.sort! User.business(@business).service_providers
      @services = PrioritySorter.sort! Service.business(@business)
      @offices = PrioritySorter.sort! Office.business(@business)

      if @office_selection.supportable.nil?
        @office_selection.update! supportable_type: 'Office', supportable_id: @offices.first
      end

      if @service_selection.supportable.nil?
        @service_selection.update! supportable_type: 'Service', supportable_id: @services.first
      end

    end
  end

  def get_setting(key, default_value)
    Setting.get_or_create(key, business_id: @business.id, value: default_value)
  end

  def setting_params
    p = params.require :setting
    p[:business_id] = @business.id
    p.permit!
  end
end

app/views/settings/_office_selection.html.haml
%h3.header
  Office Selection for your Business

%hr


.content-box
  = simple_form_for [@business, @office_selection], url: business_setting_path(@business, @office_selection) do |f|
    %input{type: "hidden", name: "hash", value: "office-selection" }/
    %input{type: "hidden", name: "setting[supportable_type]", value: "Office" }/
    - disable_selection =  @offices.length > 1 ? false : true

    .row.office-selections.no-select
      - if disable_selection
        .col.col-lg-12
          .alert.alert-info.info
            Your Business currently has less than
            %strong 2 Offices,
            check out the Offices page to &nbsp;
            = link_to 'Add more Offices', business_offices_path(@business), class: 'btn btn-info'

      .col.col-lg-12
        .selection
          %input{ id: "office-ask", type: :radio, name: "setting[office_selection_type]", value: 'office_ask', checked: ('office_ask' == @office_selection.value) }
        .heading
          %label{for: "office-ask"}
            First ask the Customer to Select a Office
            %p
              — Selection will be skipped if you have less than 2 Offices
              %span.muted — default

      .col.col-lg-12{ class: "#{disable_selection ? 'muted' : ''}" }
        .selection
          %input{ id: "office-ask-and-assume", type: :radio, name: "setting[office_selection_type]", value: 'office_ask_and_assume', checked: ('office_ask_and_assume' == @office_selection.value), disabled: disable_selection }
        .heading
          %label{for: "office-ask-and-assume"}
            Assume it is for
            = f.collection_select :supportable_id, @offices, :id, :name, {}, disabled: disable_selection
            %p but allow Customers to change the default Office

      .col.col-lg-12{ class: "#{disable_selection ? 'muted' : ''}" }
        .selection
          %input{ id: "office-assume", type: :radio, name: "setting[office_selection_type]", value: 'office_assume', checked: ('office_assume' == @office_selection.value), disabled: disable_selection }
        .heading
          %label{for: "office-assume"}
            Assume it is for
            = f.collection_select :supportable_id, @offices, :id, :name, {}, disabled: disable_selection
            %p without any option to change


    %hr
    %button.btn-save-office-selection.btn-default.btn{type: :submit}
      %i.fa.fa-save
        Save Preferences

app/views/settings/_priority.html.haml
%h3.header
  Manage Priority Selections — for Appointment Scheduling
%hr


.content-box.user-priority
  - disable_selection_providers = @service_providers.length < 2
  - disable_selection_offices   = @offices.length < 2
  - disable_selection_services  = @services.length < 2

  .row.no-select.priority-types

    .col.col-lg-4.col-md-4.offices.type{ class: "#{disable_selection_offices ? 'disabled' : ''}" }

      .row.inner
        .col.col-lg-12
          %h3 Office Priorities

          #offices-priority-container
            - for office in @offices.sort_by(&:sort_order)
              .row.item.noselect{data: {item: office.to_json }}
                .col.col-xs-2.sort_order
                  %span.count.label.label-default= office.sort_order
                .col.col-xs-7.display_name
                  = link_to office.name, business_office_path(@business, office)
                .col.col-xs-3.controls
                  %i.fa.fa-chevron-down.down
                  %i.fa.fa-chevron-up.up

        - if disable_selection_offices
          .col.col-lg-12
            .alert.alert-danger.info
              Your Business has less than
              %strong 2 Offices,
              %br
              check out the Offices page to Add more Offices&nbsp;
              %br
              %hr
              = link_to 'Add more Offices', business_offices_path(@business), class: 'btn btn-success'

    .col.col-lg-4.col-md-4.services.type{ class: "#{disable_selection_services ? 'disabled' : ''}" }
      .row.inner
        .col.col-lg-12
          %h3 Services Priorities

        - if disable_selection_services
          .col.col-lg-12
            .alert.alert-danger.info
              Your Business has less than
              %strong 2 Services,
              %br
              check out the Services page to Add more Services&nbsp;
              %br
              %hr
              = link_to 'Add more Services', business_services_path(@business), class: 'btn btn-success'

        .col.col-lg-12{ class: "#{disable_selection_providers ? 'muted' : ''}" }
          #services-priority-container
            - for service in @services.sort_by(&:sort_order)
              .row.item.noselect{data: { item: service.to_json }}
                .col.col-xs-2.sort_order
                  %span.count.label.label-default= service.sort_order
                .col.col-xs-7.display_name
                  = link_to service.name, business_service_path(@business, service)
                .col.col-xs-3.controls
                  %i.fa.fa-chevron-down.down
                  %i.fa.fa-chevron-up.up


    .col.col-lg-4.col-md-4.providers.type{ class: "#{disable_selection_providers ? 'disabled' : ''}" }
      .row.inner
        .col-lg-12
          %h3 User Provider Priorities

        - if disable_selection_providers
          .col.col-lg-12
            .alert.alert-danger.info
              Your Business has less than
              %strong 2 Service Providers,
              %br
              check out the User Staff page to Add more Users as Service Providers&nbsp;
              %br
              %hr
              = link_to 'Add more Providers', business_users_path(@business), class: 'btn btn-success'

        .col.col-lg-12{ class: "#{disable_selection_providers ? 'muted' : ''}" }
          #providers-priority-container
            - for user in @service_providers.sort_by(&:sort_order)
              .row.item.noselect{data: { item: user.to_json }}
                .col.col-xs-2.sort_order
                  %span.count.label.label-default= user.sort_order
                .col.col-xs-7.display_name
                  = link_to user.display_name, business_user_path(@business, user)
                .col.col-xs-3.controls
                  %i.fa.fa-chevron-down.down
                  %i.fa.fa-chevron-up.up



- content_for :javascript do
  :coffeescript
    window.Scp ||= {}
    window.Scp.Users = #{@service_providers.to_json}

app/views/settings/_service_selection.html.haml
%h3.header
  Service Selection for your Business

%hr


.content-box
  = simple_form_for [@business, @service_selection], url: business_setting_path(@business, @service_selection) do |f|
    %input{type: "hidden", name: "hash", value: "service-selection" }/
    %input{type: "hidden", name: "setting[supportable_type]", value: "Service" }/
    - disable_selection =  @services.length > 1 ? false : true

    .row.service-selections.no-select
      - if disable_selection
        .col.col-lg-12
          .alert.alert-info.info
            Your Business currently has less than
            %strong 2 Services,
            check out the Services page to &nbsp;
            = link_to 'Add more Services', business_services_path(@business), class: 'btn btn-info'

      .col.col-lg-12
        .selection
          %input{ id: "service-ask", type: :radio, name: "setting[service_selection_type]", value: 'service_ask', checked: ('service_ask' == @service_selection.value) }
        .heading
          %label{for: "service-ask"}
            First ask the Customer to Select a Service
            %p
              — Selection will be skipped if you have less than 2 Services
              %span.muted — default

      .col.col-lg-12{ class: "#{disable_selection ? 'muted' : ''}" }
        .selection
          %input{ id: "service-ask-and-assume", type: :radio, name: "setting[service_selection_type]", value: 'service_ask_and_assume', checked: ('service_ask_and_assume' == @service_selection.value), disabled: disable_selection }
        .heading
          %label{for: "service-ask-and-assume"}
            Assume it is for
            = f.collection_select :supportable_id, @services, :id, :name, {}, disabled: disable_selection
            %p but allow Customers to change the default Service

      .col.col-lg-12{ class: "#{disable_selection ? 'muted' : ''}" }
        .selection
          %input{ id: "service-assume", type: :radio, name: "setting[service_selection_type]", value: 'service_assume', checked: ('service_assume' == @service_selection.value), disabled: disable_selection }
        .heading
          %label{for: "service-assume"}
            Assume it is for
            = f.collection_select :supportable_id, @services, :id, :name, {}, disabled: disable_selection
            %p without any option to change
    %hr
    %button.btn-save-service-selection.btn-default.btn{type: :submit}
      %i.fa.fa-save
        Save Preferences

app/views/settings/_user_selection.html.haml
%h3.header
  User Selection for your Business

%hr


.content-box.user-selection
  - disable_selection = @service_providers.length < 2
  .row.no-select
    - if disable_selection
      .col.col-lg-12
        .alert.alert-danger.info
          Your Business has less than
          %strong 2 Service Providers,
          check out the User Staff page to &nbsp;
          = link_to 'Add more User Providers', business_users_path(@business), class: 'btn btn-success'

  = simple_form_for [@business, @user_selection], url: business_setting_path(@business, @user_selection) do |f|
    %input{type: "hidden", name: "hash", value: "user-selection" }/
    .row.no-select
      - if false
        .col.col-lg-12
          .alert.alert-info.info
            Your Business currently has less than
            %strong 2 Services,
            check out the Services page to &nbsp;
            = link_to 'Add more Services', business_services_path(@business), class: 'btn btn-info'

      .col.col-lg-12
        .selection
          %input{ id: "user-full-control", type: :radio, name: "setting[user_selection_type]", value: Setting::USER_SELECTION_FULL_CONTROL, checked: (Setting::USER_SELECTION_FULL_CONTROL == @user_selection.value) }

        .heading
          %label{for: "user-full-control"}
            Full Control
      .col.col-lg-12.info
        %p
          Customer is provided with Service Provider (User) selection first.
          %br/
          Then is provided with the next available appointments for that specific user.
        %p.small
          Additionally:
          %br
          The option to select another User or different Time will also be offered.


      .col.col-lg-12
        .selection
          %input{ id: "user-express-1", type: :radio, name: "setting[user_selection_type]", value: Setting::USER_SELECTION_EXPRESS_I, checked: (Setting::USER_SELECTION_EXPRESS_I == @user_selection.value) }

        .heading
          %label{for: "user-express-1"}
            Express I
      .col.col-lg-12.info
        %p
          Automatically select the provider and tell the customer the name of the service provider for each available slot.
        %p.small
          Additionally:
          Customer will be offered to select a different appointment time.
        .options-container


      .col.col-lg-12
        .selection
          %input{ id: "user-express-2", type: :radio, name: "setting[user_selection_type]", value: Setting::USER_SELECTION_EXPRESS_II, checked: ( Setting::USER_SELECTION_EXPRESS_II == @user_selection.value) }

        .heading
          %label{for: "user-express-2"}
            Express II

      .col.col-lg-12.info
        %p
          Automatically select the provider with no mention of who the service provider will be.
        %p.small
          Additionally:
          Customer will be offered to select a different appointment time.
        .options-container

      .col.col-lg-12
        .selection
          %input{ id: "user-express-3", type: :radio, name: "setting[user_selection_type]", value: Setting::USER_SELECTION_EXPRESS_III, checked: (Setting::USER_SELECTION_EXPRESS_III == @user_selection.value) }

        .heading
          %label{for: "user-express-3"}
            Express III
      .col.col-lg-12.info
        %p
          Customer is provided with the next available appointment for each available Service Providers
        %p.small
          Additionally:
          %br/
          Customer will be offered to select a different Appointment time.
          %br/
          Customer will be offered to select a different Service Provider.




    %hr
    %button.btn-save-service-selection.btn-default.btn{type: :submit}
      %i.fa.fa-save
        Save Preferences


    .service-provider-options
      .option
        %input{ type: :hidden, name: "setting_aux[key]", value: Setting::USER_SELECTION_PRIORITY }
        %input{ type: :hidden, name: "setting_aux[value]", value: :user_selection_priority_type }
        %input{ id: "user-selection-priority-1",
          type: :radio,
          name: "setting_aux[user_selection_priority_type]",
          value: Setting::USER_SELECTION_PRIORITY_RANDOM,
          checked: (Setting::USER_SELECTION_PRIORITY_RANDOM == @user_selection_priority.value) }
        %label{for: "user-selection-priority-1" } The Service Provider will be chosen at Random

      .option
        %input{ id: "user-selection-priority-2",
          type: :radio,
          name: "setting_aux[user_selection_priority_type]",
          value: Setting::USER_SELECTION_PRIORITY_AUTOMATIC,
          checked: (Setting::USER_SELECTION_PRIORITY_AUTOMATIC == @user_selection_priority.value) }
        %label{for: "user-selection-priority-2" } Automatic Service Provider assignment (utilizes custom priority lists)

app/views/settings/index.html.haml
%p#notice= notice

%ul#settingTabs.nav.nav-tabs.hidden{:role => "tablist"}

  %li.active{:role => "presentation"}
    %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#office_selection_content", :role => "tab", "data-hash" => "office-selection" } Office Selection

  %li{:role => "presentation"}
    %a{"aria-controls" => "home", "data-toggle" => "tab", :href => "#service_selection_content", :role => "tab", "data-hash" => "service-selection" } Service Selection

  %li{:role => "presentation"}
    %a{"aria-controls" => "profile", "data-toggle" => "tab", :href => "#user_selection_content", :role => "tab", "data-hash" => "user-selection" } User Selection

  %li{:role => "presentation"}
    %a{"aria-controls" => "messages", "data-toggle" => "tab", :href => "#priority_content", :role => "tab", "data-hash" => "priority" } Priority Management

.tab-content.hidden

  #office_selection_content.tab-pane.active{:role => "tabpanel"}
    = render 'office_selection'

  #service_selection_content.tab-pane{:role => "tabpanel"}
    = render 'service_selection'

  #user_selection_content.tab-pane{:role => "tabpanel"}
    = render 'user_selection'

  #priority_content.tab-pane{:role => "tabpanel"}
    = render 'priority'

- content_for :javascript do
  = javascript_include_tag "settings/main"

  :coffeescript
    window.Scp ||= {}
    window.Scp.Settings =
      office_selection: #{@office_selection.to_json}
      service_selection: #{@service_selection.to_json}
      user_selection: #{@user_selection.to_json}
      user_selection_priority: #{@user_selection_priority.to_json}